name: inventory-manager
recipe: laravel
config:
  webroot: public
  database: mariadb
services:
  appserver:
    type: php:8.1
  node:
    type: node:16
    build:
      - npm install
  phpmyadmin:
    type: phpmyadmin
tooling:
  npm:
    service: node
  npx:
    service: node
  node:
    service: node
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
    cmd: /app/vendor/bin/phpunit
proxy:
  phpmyadmin:
    - pma.inventory-manager.test
